directories:
  output: release/
  buildResources: build
appId: com.preparis.desktop
productName: Preparis Desktop
files:
  - '**/*'
  - '!*.ts'
  - '!*.code-workspace'
  - '!LICENSE.md'
  - '!package.json'
  - '!package-lock.json'
  - '!src/'
  - '!e2e/'
  - '!hooks/'
  - '!.angular-cli.json'
  - '!_config.yml'
  - '!karma.conf.js'
  - '!tsconfig.json'
  - '!tslint.json'
publish:
  - provider: github
    repo: preparis-desktop-deploy
    host: githuhb.com/preparis
    private: true
win:
  icon: dist
  target:
    - nsis
  certificateFile: PreparisDesktop.pfx
  certificatePassword: <stripped sensitive data>
  publisherName: Preparis
mac:
  category: public.app-category.business
  icon: dist
  target:
    - dmg
    - mas
  type: distribution
  provisioningProfile: Preparis_Desktop_Adhoc.provisionprofile
linux:
  icon: dist
  target:
    - AppImage
dmg:
  title: Preparis Desktop
mas:
  provisioningProfile: Preparis_Desktop_Dist.provisionprofile
pkg:
  identity: '3rd Party Mac Developer Installer: Preparis (Q786FQYE46)'
electronVersion: 3.0.10
